# Generated by Django 3.0.3 on 2020-04-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20200220_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
