# Generated by Django 3.0.5 on 2020-04-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20200418_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['start_date'], 'verbose_name': 'media', 'verbose_name_plural': 'media items'},
        ),
    ]
