# Generated by Django 3.0.6 on 2020-05-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_media_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='start',
            new_name='jump',
        ),
    ]
