# Generated by Django 3.0.6 on 2020-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_auto_20200509_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='trim',
            field=models.IntegerField(default=0),
        ),
    ]
