"""
One-off generator for data/bts_tail_decode_2001-09.csv and
data/faa_registry_2001-09.csv — the era-correct aircraft-type reference used
by the flight-metadata feature (2026-07-09).

Why this exists
---------------
BTS's canonical September 2001 On-Time PREZIP (file dated 2018-09-18; a fresh
download today is byte-identical) has a mangled Tail_Number column — an
artifact of a botched EBCDIC conversion on BTS's side:

- letters S-Z appear as raw EBCDIC bytes 0xE2-0xE9 (latin-1 "â ã ä å æ ç è é")
- EBCDIC spaces (0x40) appear as "@" — Southwest reported truncated tails
  padded with these ("N368@@" = "N368", really N368SW)
- the FINAL character was run through a zoned-decimal digit conversion:
  a trailing letter A-I / J-R shows as the digit of its low nibble
  ("N334A1" = N334AA, US Airways "N123äâ" = N123US)
- some rows are right-shifted with a leading "-" (last character lost)
- American (AA) and American Eagle (MQ) largely reported internal ship
  numbers, not registrations — those rows are structurally unrecoverable

Method
------
Candidates for each (carrier, raw) pair are generated by inverting the
mangling above, then accepted only when unambiguous against, in order:
(1) the carrier's own clean tails from the 2002-09 / 2004-01 BTS months
    (tail encoding is clean from 2002-09 onward),
(2) the September 2001 FAA registry fleet (unique candidate),
(3) carrier-dominant registration suffix (>3x dominance) or, for truncated
    Southwest-style reports, unique suffix-completion among aircraft whose
    registry RANT matches the carrier (e.g. "SOUTHWEST AIRLINES").
Every accepted tail must exist in the full September 2001 FAA registry.

Sources (all public):
- FAA aircraft registry snapshot dated 2001-09-29 (18 days after 9/11),
  recovered from the Wayback Machine:
  https://web.archive.org/web/20011012040906id_/http://registry.faa.gov/database/ar102001.zip
  (MASTER = registrations incl. N334AA/N612UA/N644AA/N591UA; ACFTREF =
  make/model reference). This is era-correct: N-numbers are reassigned over
  time, so the CURRENT registry must not be used for 2001 data.
- BTS On-Time PREZIPs 2001-09 (mangled input), 2002-09 and 2004-01 (clean
  reference months): https://transtats.bts.gov/PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_YYYY_M.zip
- BTS Schedule B-43 was evaluated and rejected: its public digital series
  only begins with the 2006 filing year.

Outputs
-------
- data/faa_registry_2001-09.csv  TAIL_NUMBER,MANUFACTURER,MODEL for every
  fixed-wing multi-engine aircraft with >=10 seats registered 2001-09-29
  (the fleet.py contract).
- data/bts_tail_decode_2001-09.csv  CARRIER,RAW_TAIL,TAIL_NUMBER mapping the
  mangled September 2001 BTS values to real registrations (~54% of window
  flight-rows resolve; misses are dominated by AA/MQ ship numbers).

Coverage measured on the 2001-09-09..12 window: 54.5% of flight rows gain a
tail, 53.5% gain an aircraft type. Not re-run by CI; kept for provenance and
regeneration. Requires the three PREZIPs and the extracted ar102001.zip in
--work-dir.
"""

import argparse
import glob
import itertools
import os
import re
from collections import Counter, defaultdict

import pandas as pd

from flight_recon.fleet import load_fleet

WINDOW = ("2001-09-09", "2001-09-12")
EBCDIC_SZ = {chr(0xE2 + i): chr(ord("S") + i) for i in range(8)}
CARRIER_REGISTRANT = {
    "AA": "AMERICAN AIRLINES", "WN": "SOUTHWEST AIRLINES", "UA": "UNITED AIR LINES",
    "DL": "DELTA AIR LINES", "US": "US AIRWAYS", "NW": "NORTHWEST AIRLINES",
    "CO": "CONTINENTAL AIRLINES", "AS": "ALASKA AIRLINES", "HP": "AMERICA WEST",
    "TW": "TRANS WORLD", "MQ": "SIMMONS|AMERICAN EAGLE|EXECUTIVE AIRLINES|FLAGSHIP",
    "KH": "ALOHA",
}


def build_registry_csv(work_dir, out_csv):
    ref = pd.read_csv(os.path.join(work_dir, "ACFTREF"), dtype=str,
                      low_memory=False, encoding="latin-1")
    ref.columns = [c.strip() for c in ref.columns]
    m = pd.read_csv(os.path.join(work_dir, "MASTER"), dtype=str, low_memory=False,
                    encoding="latin-1", on_bad_lines="skip")
    m.columns = [c.strip() for c in m.columns]
    m["tail_n"] = "N" + m["N-NUMBER"].str.strip()
    m["code"] = m["MFR MDL CODE"].str.strip()
    ref["code"] = ref["CODE"].str.strip()
    ref["mfr"] = ref["MFR-NAME"].str.strip().str.title()
    ref["model"] = ref["MODEL"].str.strip()
    j = m.merge(ref[["code", "mfr", "model", "TYPE-ACFT", "NO-SEATS"]], on="code", how="left")
    j["NO-SEATS"] = pd.to_numeric(j["NO-SEATS"], errors="coerce").fillna(0)
    big = j[(j["TYPE-ACFT"].str.strip() == "5") & (j["NO-SEATS"] >= 10)]
    out = (big[["tail_n", "mfr", "model"]].dropna()
           .rename(columns={"tail_n": "TAIL_NUMBER", "mfr": "MANUFACTURER", "model": "MODEL"})
           .drop_duplicates(subset=["TAIL_NUMBER"]))
    out.to_csv(out_csv, index=False)
    registrant = {"N" + r["N-NUMBER"].strip(): str(r["NAME"]).strip() for _, r in m.iterrows()}
    return set(registrant), registrant


def zoned(digit):
    n = int(digit)
    return [chr(ord("A") + n - 1), chr(ord("J") + n - 1)] if 1 <= n <= 9 else []


def narrow(raw):
    """Invert the mangling -> (candidate tails, is_truncated_prefix)."""
    t = "".join(EBCDIC_SZ.get(ch, ch) for ch in raw.strip()).replace("@", "").replace("`", "")
    shifted = t.startswith("-")
    t = t.lstrip("-")
    if not t:
        return [], False
    if not t.startswith("N"):
        t = "N" + t
    if shifted or len(t) < 6:
        return [t], True
    cands = [t] + ([t[:-1] + L for L in zoned(t[-1])] if t[-1].isdigit() else [])
    return cands, False


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    p.add_argument("--work-dir", required=True,
                   help="dir holding MASTER, ACFTREF (from ar102001.zip), the raw "
                        "2001-09 BTS CSV, and b2002/b2004 dirs with clean months")
    p.add_argument("--raw-2001", required=True, help="raw BTS 2001-09 monthly CSV")
    p.add_argument("--out-dir", default=os.path.join(os.path.dirname(__file__), os.pardir, "data"))
    a = p.parse_args()

    universe, registrant = build_registry_csv(
        a.work_dir, os.path.join(a.out_dir, "faa_registry_2001-09.csv"))
    fleet = load_fleet(os.path.join(a.out_dir, "faa_registry_2001-09.csv"))

    ref_by_carrier = defaultdict(set)
    for d in ("b2002", "b2004"):
        f = glob.glob(os.path.join(a.work_dir, d, "*.csv"))[0]
        t = pd.read_csv(f, usecols=["Reporting_Airline", "Tail_Number"],
                        encoding="latin-1", dtype=str, low_memory=False).dropna()
        for c, x in zip(t.Reporting_Airline, t.Tail_Number):
            x = x.strip()
            if x and "NKNO" not in x and len(x) >= 5:
                ref_by_carrier[c].add(x if x.startswith("N") else "N" + x)

    def owner_ok(tail, carrier):
        pat = CARRIER_REGISTRANT.get(carrier)
        return bool(pat and re.search(pat, registrant.get(tail, "")))

    def resolve(carrier, raw):
        cands, prefix = narrow(raw)
        if not cands:
            return None
        if prefix:
            base = cands[0]
            ext = [r for r in fleet if r.startswith(base) and owner_ok(r, carrier)]
            if len(ext) == 1 or (ext and len({fleet[r] for r in ext}) == 1):
                return sorted(ext)[0]
            hits = {r for r in ref_by_carrier.get(carrier, ()) if r.startswith(base)}
            return hits.pop() if len(hits) == 1 else None
        in_ref = [c for c in cands if c in ref_by_carrier.get(carrier, ())]
        if len(in_ref) == 1:
            return in_ref[0]
        in_fleet = [c for c in cands if c in fleet]
        if len(in_fleet) == 1:
            return in_fleet[0]
        owned = [c for c in in_fleet if owner_ok(c, carrier)]
        return owned[0] if len(owned) == 1 else None

    df = pd.read_csv(a.raw_2001, usecols=["FlightDate", "Reporting_Airline", "Tail_Number"],
                     encoding="latin-1", dtype=str, low_memory=False)
    w = df[(df.FlightDate >= WINDOW[0]) & (df.FlightDate <= WINDOW[1])]
    pairs = sorted({(c, t) for c, t in zip(w.Reporting_Airline, w.Tail_Number.fillna(""))
                    if t and "NKNO" not in t})
    res = {(c, t): resolve(c, t) for c, t in pairs}

    suffix = defaultdict(Counter)
    for (c, _), r in res.items():
        if r and r[-2:].isalpha():
            suffix[c][r[-2:]] += 1
    for (c, t), r in list(res.items()):
        if r:
            continue
        cands, prefix = narrow(t)
        pool = ([x for x in cands if x in fleet] if not prefix else
                [x for x in fleet if cands and x.startswith(cands[0])])
        if len(pool) > 1:
            ranked = sorted(pool, key=lambda x: -suffix[c].get(x[-2:], 0))
            top = suffix[c].get(ranked[0][-2:], 0)
            if top > 3 and top > 3 * suffix[c].get(ranked[1][-2:], 0):
                res[(c, t)] = ranked[0]

    rows = [(c, t, r) for (c, t), r in sorted(res.items()) if r and r in universe]
    out = os.path.join(a.out_dir, "bts_tail_decode_2001-09.csv")
    pd.DataFrame(rows, columns=["CARRIER", "RAW_TAIL", "TAIL_NUMBER"]).to_csv(out, index=False)
    print(f"{out}: {len(rows)} mappings")


if __name__ == "__main__":
    main()
