version: '3'

services:
#  db:
#    image: mysql:5.7
#    ports:
#      - '3306:3306'
#    environment:
#       MYSQL_DATABASE: 'rt911'
#       MYSQL_USER: 'rt911'
#       MYSQL_PASSWORD: 'CT7SQzldZqwS2pinf6s9'
#       MYSQL_ROOT_PASSWORD: 'CT7SQzldZqwS2pinf6s9'
  web:
    build: .
    # python manage.py loaddata fixtures/initial.json &&
    command: >
        bash -c "python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py shell -c 'from django.contrib.auth.models import User; User.objects.filter(email=\"rt911@robbiebyrd.com\").delete(); User.objects.create_superuser(\"rt911\", \"rt911@robbiebyrd.com\", \"rt911\")' &&
        gcloud app deploy &&
        python manage.py runserver  0.0.0.0:8000"
    volumes:
      - .:/rt911
    ports:
      - "8000:8000"
    restart: always
