"""
Prefect flow: reconstruct flight trajectories for a date window and load them
into Directus.

Parameters
----------
start / end       inclusive YYYY-MM-DD window
flights_path      BTS On-Time CSV inside the job container (baked-in sample by
                  default; mount real monthly drops via the work pool's volume)
airports_path     airport reference CSV (code,lat,lon,utc_offset)
run_id            provenance tag; autogenerated UUID4 hex when omitted
directus_url      overrides $DIRECTUS_URL
positions_loader  "copy" (default: Postgres COPY fast path, needs $RT911_DB_DSN)
                  or "items" (Directus items API — hours for real windows)

$DIRECTUS_API_TOKEN (and $RT911_DB_DSN for the copy path) must be in the
environment (injected from the flight-recon-secrets Kubernetes Secret —
never parameters, never logged).
"""

import os
import uuid
from pathlib import Path

from prefect import flow, get_run_logger, task

from flight_recon.directus import COLLECTIONS, DirectusClient
from flight_recon.fleet import load_fleet
from reconstruct import reconstruct

# NB: scalar retry_delay_seconds — list-valued delays 422 on this server (see
# packages/tools/video-grabber/CLAUDE.md).
NETWORK_RETRIES = dict(retries=4, retry_delay_seconds=15, retry_jitter_factor=0.3)


def _client(directus_url):
    url = directus_url or os.environ["DIRECTUS_URL"]
    token = os.environ["DIRECTUS_API_TOKEN"]
    return DirectusClient(url, token)


@task
def validate_inputs(start, end, flights_path, airports_path):
    log = get_run_logger()
    for p in (flights_path, airports_path):
        if not Path(p).is_file():
            raise FileNotFoundError(f"input artifact not found in job container: {p}")
    if str(end) < str(start):
        raise ValueError(f"end {end} precedes start {start}")
    log.info("inputs ok: %s..%s flights=%s airports=%s", start, end, flights_path,
             airports_path)


@task
def run_reconstruction(start, end, flights_path, airports_path, fleet_path=None):
    log = get_run_logger()
    fleet = None
    if fleet_path and Path(fleet_path).is_file():
        fleet = load_fleet(fleet_path)
        log.info("fleet reference loaded: %d tails from %s", len(fleet), fleet_path)
    else:
        log.warning("no fleet reference at %s — aircraft_type will be null", fleet_path)
    positions, tracks, summary, _ = reconstruct(start, end, flights_path, airports_path,
                                                fleet=fleet)
    typed = sum(1 for t in tracks if t["properties"]["aircraft_type"])
    log.info("reconstructed %d flights -> %d positions, %d tracks (%d with "
             "aircraft_type); skipped %d (cancelled_by_day=%s)",
             summary["flights_reconstructed"], summary["positions_count"],
             summary["tracks_count"], typed, summary["skipped_count"],
             summary["cancelled_by_day"])
    return positions, tracks, summary


@task(**NETWORK_RETRIES)
def ensure_schema(directus_url):
    log = get_run_logger()
    client = _client(directus_url)
    try:
        for name in COLLECTIONS:
            for action in client.ensure_collection(name):
                log.warning("schema change: %s", action)
        log.info("schema ensured for %s", list(COLLECTIONS))
    finally:
        client.close()


@task(**NETWORK_RETRIES)
def load_positions(positions, run_id, start, end, directus_url, positions_loader):
    log = get_run_logger()
    if positions_loader == "copy":
        # Fast path: the items API sustains only ~300 rows/s on rt911-api;
        # a real multi-day window is millions of rows. See flight_recon/pgcopy.py.
        from flight_recon.pgcopy import copy_positions
        dsn = os.environ["RT911_DB_DSN"]
        deleted, inserted = copy_positions(dsn, positions, run_id, start, end)
        log.info("flight_positions: COPYed %d rows (deleted %d, run_id=%s)",
                 inserted, deleted, run_id)
        return inserted
    client = _client(directus_url)
    try:
        deleted = client.delete_window("flight_positions", start, end)
        if deleted:
            log.warning("idempotent reload: deleted %d flight_positions rows in "
                        "[%s, %s] before insert", deleted, start, end)
        rows = [{**p, "run_id": run_id} for p in positions]
        inserted = client.insert_many("flight_positions", rows)
        log.info("flight_positions: inserted %d rows (run_id=%s)", inserted, run_id)
        return inserted
    finally:
        client.close()


@task(**NETWORK_RETRIES)
def load_tracks(tracks, run_id, start, end, directus_url):
    log = get_run_logger()
    client = _client(directus_url)
    try:
        deleted = client.delete_window("flight_tracks", start, end)
        if deleted:
            log.warning("idempotent reload: deleted %d flight_tracks rows in "
                        "[%s, %s] before insert", deleted, start, end)
        rows = [{**feature["properties"], "geometry": feature["geometry"],
                 "run_id": run_id} for feature in tracks]
        # geometry-heavy rows: insert_many's size-aware batching keeps each
        # request under Directus's 1 MB MAX_PAYLOAD_SIZE
        inserted = client.insert_many("flight_tracks", rows, chunk=250)
        log.info("flight_tracks: inserted %d rows (run_id=%s)", inserted, run_id)
        return inserted
    finally:
        client.close()


SKIPPED_DETAIL_CAP = 2000


def trim_summary(summary, run_id):
    """Shape a reconstruct() summary for the ledger row. Full skip detail can
    be megabytes (a 9/11-scale window skips 35k+ flights, mostly cancelled —
    already aggregated in cancelled_by_day), which blows Directus's 1 MB
    payload cap. Keep per-reason counts plus capped non-cancelled detail."""
    by_reason = {}
    for s in summary["skipped"]:
        by_reason[s["reason"]] = by_reason.get(s["reason"], 0) + 1
    detail = [s for s in summary["skipped"] if s["reason"] != "cancelled"]
    return {**summary, "run_id": run_id,
            "skipped": detail[:SKIPPED_DETAIL_CAP],
            "skipped_by_reason": by_reason}


@task(**NETWORK_RETRIES)
def record_run_summary(summary, run_id, directus_url):
    log = get_run_logger()
    client = _client(directus_url)
    try:
        client.insert_one("reconstruction_runs", trim_summary(summary, run_id))
        log.info("reconstruction_runs: recorded run %s", run_id)
    finally:
        client.close()


@flow(name="reconstruct-flights", log_prints=True)
def reconstruct_flights(
    start: str = "2001-09-09",
    end: str = "2001-09-12",
    flights_path: str = "/app/data/sample_bts_2001-09-09_2001-09-12.csv",
    airports_path: str = "/app/data/airports.csv",
    fleet_path: str | None = "/app/data/b43_2001.csv",
    run_id: str | None = None,
    directus_url: str | None = None,
    positions_loader: str = "copy",  # "copy" (Postgres COPY) | "items" (Directus API)
    skip_positions: bool = False,    # tracks-only backfill: leave flight_positions alone
):
    log = get_run_logger()
    run_id = run_id or uuid.uuid4().hex
    log.info("run_id=%s window=[%s, %s] positions_loader=%s skip_positions=%s",
             run_id, start, end, positions_loader, skip_positions)

    validate_inputs(start, end, flights_path, airports_path)
    positions, tracks, summary = run_reconstruction(start, end, flights_path,
                                                    airports_path, fleet_path)
    ensure_schema(directus_url)
    if skip_positions:
        n_pos = 0
        log.warning("skip_positions=True: flight_positions untouched (tracks-only backfill)")
    else:
        n_pos = load_positions(positions, run_id, start, end, directus_url, positions_loader)
    n_trk = load_tracks(tracks, run_id, start, end, directus_url)
    record_run_summary(summary, run_id, directus_url)

    log.info("done: %d positions + %d tracks in Directus, run_id=%s", n_pos, n_trk, run_id)
    return {"run_id": run_id, **summary}


if __name__ == "__main__":
    # Local/dev execution without a deployment: python -m flight_recon.flow
    reconstruct_flights()
