# Generated by Django 3.0.1 on 2021-01-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_timemarkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_marker', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='TimeMarkers',
        ),
    ]
