# Generated by Django 3.1.8 on 2021-05-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20210125_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
