# Generated by Django 3.1.8 on 2021-05-23 21:27

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_marker_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='time_marker',
            field=models.DateTimeField(default=media.models.default_start_time),
        ),
    ]
