# Generated by Django 3.1.8 on 2021-05-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20210523_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={'ordering': ['-time_marker']},
        ),
    ]
