# Generated by Django 3.1.8 on 2021-06-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20210523_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='media_item',
            field=models.ManyToManyField(blank=True, to='media.Media'),
        ),
    ]
