# Generated by Django 3.1.8 on 2021-06-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20210601_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='type_of',
        ),
    ]
