# Generated by Django 3.1.8 on 2021-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_remove_collection_type_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='media_item',
            field=models.ManyToManyField(blank=True, limit_choices_to={'approved': True}, to='media.Media'),
        ),
    ]
