# Generated by Django 3.1.12 on 2021-06-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20210611_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='media_item',
        ),
        migrations.AddField(
            model_name='collection',
            name='media',
            field=models.ManyToManyField(blank=True, limit_choices_to={'approved': True}, to='media.Media'),
        ),
    ]
