# Generated by Django 3.1.8 on 2021-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20210613_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='calc_duration',
            field=models.IntegerField(default=0),
        ),
    ]
