# Generated by Django 3.1.13 on 2021-08-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_media_calc_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
