# Generated by Django 3.1.8 on 2021-08-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_media_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='calc_duration',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
