# Generated by Django 3.1.8 on 2021-08-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_auto_20210828_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-sort', 'start_date'], 'verbose_name': 'media', 'verbose_name_plural': 'media items'},
        ),
    ]
