# Generated by Django 3.1.14 on 2022-01-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_auto_20210828_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='tz',
        ),
    ]
