# Generated by Django 3.2.12 on 2022-03-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_auto_20220312_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='tz',
        ),
        migrations.RemoveField(
            model_name='media',
            name='tz_offset',
        ),
        migrations.AddField(
            model_name='media',
            name='timezone',
            field=models.TextField(blank=True, default='EDT'),
        ),
        migrations.AddField(
            model_name='media',
            name='timezone_offset',
            field=models.IntegerField(default=0),
        ),
    ]
