# Generated by Django 3.2.12 on 2022-03-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_auto_20220312_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='timezone',
            field=models.CharField(choices=[('CST', 'Central Standard Time'), ('ADT', 'Atlantic Daylight Time'), ('BST', 'British Summer Time'), ('CST', 'Central Standard Time'), ('CDT', 'Central Daylight Time'), ('EDT', 'Eastern Daylight Time'), ('EST', 'Eastern Standard Time'), ('MSD', 'Moscow Summer Time'), ('MDT', 'Mountain Daylight Time'), ('MST', 'Mountain Standard Time'), ('PDT', 'Pacific Daylight Time'), ('PST', 'Pacific Standard Time'), ('UTC', 'Coordinated Universal Time'), ('JST', 'Japan Standard Time'), ('CEST', 'Central European Summer Time'), ('EEST', 'Eastern European Summer Time')], max_length=5),
        ),
    ]
