# Generated by Django 3.2.13 on 2022-04-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_remove_media_timezone_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='calc_duration',
        ),
    ]
