# Generated by Django 3.2.13 on 2022-05-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_alter_media_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='timezone',
            field=models.CharField(choices=[('Asia/Baghdad', 'ADT - Atlantic Daylight Time'), ('Europe/London', 'BST - British Summer Time'), ('America/Chicago', 'CDT - Central Daylight Time'), ('Europe/Paris', 'CEST - Central European Summer Time'), ('Asia/Shanghai', 'CST - China Standard Time'), ('America/New_York', 'EDT - Eastern Daylight Time'), ('Asia/Jerusalem', 'EEST - Eastern European Summer Time'), ('Asia/Tokyo', 'JST - Japan Standard Time'), ('Europe/Moscow', 'MSD - Moscow Daylight Time')], max_length=255),
        ),
    ]
