# Generated by Django 3.0.5 on 2020-04-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20200418_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='media',
            name='mediaType',
        ),
    ]
