# Generated by Django 3.0.5 on 2020-04-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20200419_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
