# Generated by Django 3.0.6 on 2020-05-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20200426_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='vidid',
        ),
    ]
