# Generated by Django 3.0.6 on 2020-05-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_media_vidid'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
