# Generated by Django 3.0.3 on 2020-06-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_auto_20200516_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='full',
            new_name='full_title',
        ),
        migrations.AddField(
            model_name='media',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
