# Generated by Django 3.0.3 on 2020-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_auto_20200624_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='media',
            name='image_caption',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
