# Generated by Django 3.0.3 on 2020-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_auto_20200703_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
