# Generated by Django 3.0.7 on 2020-08-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_media_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_caption',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(null=True, to='media.Tag'),
        ),
    ]
