# Generated by Django 3.0.7 on 2020-08-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_auto_20200809_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='typeOf',
            field=models.ManyToManyField(null=True, to='media.TagType'),
        ),
    ]
