# Generated by Django 3.0.3 on 2020-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_auto_20200814_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.CharField(max_length=5),
        ),
    ]
