# Generated by Django 3.0.3 on 2020-08-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_auto_20200828_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, to='media.Tag'),
        ),
    ]
