# Generated by Django 3.0.3 on 2020-08-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_auto_20200828_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='full_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
