# Generated by Django 3.0.3 on 2020-08-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_auto_20200828_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mute',
            field=models.BooleanField(default=False),
        ),
    ]
